import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="bg-black text-white min-h-screen">
        <nav className="flex gap-6 p-4 border-b border-gray-700">
          <Link href="/dashboard">Dashboard</Link>
          <Link href="/itch">Itch</Link>
          <Link href="/sleep">Sleep</Link>
        </nav>

        <main className="p-6">
          {children}
        </main>
      </body>
    </html>
  );
}
